### PR TITLE
swiping via mouse

### PR DESCRIPTION
**Pull request by wrabel**
Hi

In care of PC users I added options to be able to swipe through panels with the mouse.

### CODE REVIEW

**Comment by wrabel** [comment]
Hi 
first two corrected, unfortunately I do not know what you mean in point 3.

btw I love that you used the zod to do it.

**Comment by zanna-37** [comment]
I did some minor cosmetic changes, but nothing special.
Thank you again for your work! Everything will go live with the new release.

P.S.
> I do not know what you mean in point 3.

I Just added the dot at the end of the sentence. =)

```js
logd("Ignoring " + interactionType + ": swiping via mouse is disabled.");
                                                         This dot ---^
```

**Comment by zanna-37** [comment]
Can you test the new pre-release `v1.13.0`? Everything should be working.

**Comment by wrabel** [comment]
looks fine

**Comment by zanna-37** [comment]
@wrabel I learned a new lesson today. TouchEvent might not be defined. For example on Firefox when the device has no touch support. See issue `#62`. Anyway, it's fixed now. =)

**Comment by wrabel** [comment]
thanks for information :)

**Pull request merged**
