### PR TITLE
Added new config param animate_duration

### PR DESCRIPTION
**Pull request by ambroseus**
Added ability to control animate duration via config param `animate_duration`

### CODE REVIEW

**Comment by zanna-37** [comment]
Thank you very much for your PR.
What is your use case? It is too fast or too slow for you? Or do you just want to add customization?

**Comment by ambroseus** [comment]
> Thank you very much for your PR. What is your use case? It is too fast or too slow for you? Or do you just want to add customization?

it's a little bit slow for my experience :) wanna reduce to 100 ms

**Comment by ambroseus** [comment]
running tests:
Screenshot from 2023-06-24 13-50-01

**Comment by ambroseus** [comment]
waiting for approve, merge and release 😏

**Comment by zanna-37** [comment]
I took the liberty of fixing some minor issues and rewrite the commit message to adhere to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by zanna-37** [comment]
It's on the pre-release v1.12.0. Do you confirm it's working?

**Comment by ambroseus** [comment]
yes, just switched to pre-release version on my  ha instance, set duration to 100 ms - it works as expected 🎉

**Comment by ambroseus** [comment]
and i'm happy now :)

**Comment by zanna-37** [comment]
Me too, and thank you very much for your contribution! Much appreciated 😊

**Pull request merged**
